### ISSUE TITLE
Panel with RAM bug

### ISSUE THREAD

**Issue by ElBigodon** [mesacarlos/WebConsole#1]
there is a bug in which panel RAM consumption is negative, demonstrative images:

BUG - http://prnt.sc/ox5ni8
START.bat- http://prnt.sc/ox5nvk
Java Version - http://prnt.sc/ox5o52

**Comment by mesacarlos** [comment]
Thank you for pointing this out. I've just released a new version, i think that now it should be resolved.

https://github.com/mesacarlos/WebConsole/releases/tag/v1.2

Please reply if you still have issues with the update.
