### ISSUE TITLE
ssl cofiguration

### ISSUE THREAD

**Issue by Toomas633** [mesacarlos/WebConsole#101]
Hi,
I'm currently setting up the plugin on my server and i plan to use a self hosted ssl secured client server, so how would i go about securing the server itself with ssl. 
I tried using certbot, but it asked me for webroot location?
I do have a cloudflare domain that i could use but i have no idea how. 
The tutorial page is a little lacking on the ssl setup part.

**Comment by mesacarlos** [comment]
Hi,
Some users tried using cloudflare SSL certificate with no luck: https://github.com/mesacarlos/WebConsole/issues/47
Using certbot you can create a letsencrypt certificate for your domain, and then use that certificate with the tutorial on the wiki to generate the file needed by webconsole.
You can find instructions on how to generate your certificate using certbot for your server at https://eff-certbot.readthedocs.io/en/stable/using.html#getting-certificates-and-choosing-plugins (run with certbot certainly if you do not have an apache server or any other software installed)

**Comment by Toomas633** [comment]
Thanks, got it now.
