### ISSUE TITLE
Servers aren't saved

### ISSUE THREAD

**Issue by SpiziTV** [mesacarlos/WebConsole#110]
Hello, I encounter a small problem when using the WebConsole plugin
Everything is perfectly configured, I have the display of the consoles etc.
However, if I add a server from my computer, although I have the console etc, I don't have it on my phone, I have to add the servers again on my phone
Then the same on all other devices

The login information (I'm not talking about the password) is not saved so you have to constantly re-enter everything
Having nearly twenty servers on a Network is very annoying

thanks in advance
You can contact me on Discord: SpiziTV#6458

**Comment by mesacarlos** [comment]
Hello,
That's correct. Servers are not synced between clients as all your private info (server list, passwords, config, etc.) is only saved locally.
However, you can create a JSON file containing all your servers info and that JSON will be loaded into your client. More info: https://github.com/mesacarlos/WebConsole/pull/83
