### ISSUE TITLE
Keeping servers stored on the website instead of the users computer

### ISSUE THREAD

**Issue by GalacticGreenLemon** [mesacarlos/WebConsole#114]
Is there a way for me to keep the servers from "your servers" stored on my website so not every user has to add them manually? Cause I want this to be used by multiple people and it would be better for them to not have to add the servers themselves.

**Comment by mesacarlos** [comment]
Hi,
Yes, it is possible to auto-load a list of servers. You can find info here: https://github.com/mesacarlos/WebConsole/pull/83

**Comment by GalacticGreenLemon** [comment]
Tank you!
