### ISSUE TITLE
password not being saved in config

### ISSUE THREAD

**Issue by TheMightyMcGrew** [mesacarlos/WebConsole#115]
MC 1.18.1 Fabric mod version 2.4.0
the admin name user type and password arent being saved in the config folder. If i change the password and save the file. close and reopen, it shows it took and saved it, but as soon as i restart the server for the changes to take effect it reverts to default ADMIN admin name and password

**Comment by TheMightyMcGrew** [comment]
> 

I would love to, but i cant find the issues button there. Does he have issues disabled?

**Comment by t2pellet** [comment]
Hey, sorry looks like I did - that’s fixed now!
