### ISSUE TITLE
Unable to show colour on v2.4

### ISSUE THREAD

**Issue by huizichin** [mesacarlos/WebConsole#116]
![image](https://user-images.githubusercontent.com/16850884/172512913-7fb9b526-81aa-4130-adf8-b84d88813a38.png)
used to be fine on v2.3, not sure why colour coding is not working on v2.4
Running 1.18.2 purpur, TPS not working which is already issued.

**Comment by mesacarlos** [comment]
Solved!

I'm planning to publish a update with general improvements in the upcoming days or weeks. I'll publish this fix there, but if you don't want to wait until then, just download this new version of the client/scripts/WebConsole.js file. Replacing it will do the trick
!

[WebConsole.zip](https://github.com/mesacarlos/WebConsole/files/8863312/WebConsole.zip)
