### ISSUE TITLE
[Question] Can not load ServerConsole

### ISSUE THREAD

**Issue by ErythroCraft** [mesacarlos/WebConsole#117]
Hello

I'm new with this plugin.

So. I installed the plugin on my server and started the web console at a webserver.
My server is hosted on **server.erythrocraft.de:34683**

I added a new server in the web browser, but the port is not exeptable or the server could not find.

The port 8080 is reserved for the mein page http://server.erythrocraft.de

What misstake I have?

**Comment by mesacarlos** [comment]
Hi,

First, you need to configure plugin using the file config.yml in your server (folder plugins/WebCOnsole/config.yml)
There, set a port and a password, and reload the server
Then, verify that the port you just set in the config file is open in your firewall and reachable from Internet.

Lastly, just open the client [here](https://mesacarlos.es/webconsole/client-v2.5-beta/) or, if you prefer, you can host it in your webserver (Apache, etc..), and add the server

**Comment by ErythroCraft** [comment]
Sorry for the post.

I added a new testport called 25565 and now works fine.

The port 34683 and 8080 was reserved.
Password is working fine, too.

Thank you
