### ISSUE TITLE
SSL Types?

### ISSUE THREAD

**Issue by AceSardonyx** [mesacarlos/WebConsole#121]
What kind of SSL types can be used?
I've tried using OpenSSL to generate a jks certificate but the server decided not to connect due to an ssl issue.
If we are unable to use other ssl types,, perhaps a guide on how to get a *working* jks certificate would be helpful.

**Comment by mesacarlos** [comment]
Hello,
Sorry for the late response.

Code is currently only officially supporting JKS certificates.
You can learn how to get a working JKS certificate here: https://github.com/mesacarlos/WebConsole/wiki/SSL-Configuration
You can get more detailed, technical information about how this works in the Java-WebSocket repo https://github.com/TooTallNate/Java-WebSocket/wiki/FAQ:-Secure-WebSockets#overview
