### ISSUE TITLE
Web Server not connecting to the server

### ISSUE THREAD

**Issue by Entity0165** [mesacarlos/WebConsole#125]
So I have my Minecraft server running on a computer port forwarded with TCPShield. I am also running the web console on a raspberry pi with Nginx and no port forwarding. 

There isn't any video of the plugin that makes explaining the whole process clear.

What combination of ips/domains and ports am I supposed to put here? I assume it should be the local address of the Minecraft server as its all on the same network. Then the port should be 8080 because that's what's in the config of the plugin right? I'm not trying to open anymore ports.
![image](https://user-images.githubusercontent.com/81374481/194069046-c760339d-ce90-4e62-8da9-eeb624bb35f5.png)

If someone could help me out with this that would be great.

**Comment by mesacarlos** [comment]
Hello, yes, that's correct.
You can use your local IP (within your local network) or your public IP. Port is the one placed in the config.yml file.
WebConsole starts a WebSocket server in that port. You can check if it is accesible to you using tools like this one:
https://www.yougetsignal.com/tools/open-ports/
Typing there the same IP and port should throw a "Port is open" message. If not, WebConsole is not visible and client will not be able to connect.

**Comment by Entity0165** [comment]
Oh I just needed to wait for it all to register. Thanks!
