### ISSUE TITLE
How can I translate it into Traditional Chinese?

### ISSUE THREAD

**Issue by angela0930** [mesacarlos/WebConsole#126]
How can I translate it into Traditional Chinese?
I see that  only have Simplified Chinese here.

**Comment by mesacarlos** [comment]
Hello,
To translate the WebConsole plugin (messages printed on Minecraft console) you need to copy and translate the https://github.com/mesacarlos/WebConsole/blob/master/phrases_en.properties file. You can find examples in the same directory for many other languages. Don't forget to put the correct locale in the file name.

To translate the WebConsole client (Webpage), you can find examples here: https://github.com/mesacarlos/WebConsole/tree/master/client/src/assets/i18n
Just copy the file and translate its contents.
Also, to make this language available in the client:

- Add it to the HTML in the following file: https://github.com/mesacarlos/WebConsole/blob/7dfd2081d9be2e2d50566ee0703b62889ffe6288/client/src/app/content/settings/settings.component.html#L70
- Add it to the language list in the following file: https://github.com/mesacarlos/WebConsole/blob/7dfd2081d9be2e2d50566ee0703b62889ffe6288/client/src/app/core/language.module.ts#L23

**Comment by angela0930** [comment]
I suggest you change phrases_zh.properties to phrases_zh-cn.properties.

**Comment by angela0930** [comment]
I'll give you the translated file(.zip)
[phrases_zh-tw.zip](https://github.com/mesacarlos/WebConsole/files/9972653/phrases_zh-tw.zip)

**Comment by mesacarlos** [comment]
Thank you for your contribution! 2295ad67a4e7c3f7ccf65fa9d3ebfaf9fd8f8b32
