### ISSUE TITLE
Port doesnt seem to be running even though its open on my server and firewall

### ISSUE THREAD

**Issue by pandadevv5495** [mesacarlos/WebConsole#132]
Port checker says its closed and I know as a fact I opened it on my firewall(was checked by a professional). My server is on 1.19.2 if anyone can help that would be great, another thing is I have it proxied through waterfall but it didnt even work when it wasnt.

**Comment by mesacarlos** [comment]
Hello,
Maybe you have any other additional information you can provide to try find the issue?

If the port checker is unable to make a connection with your server, then something in the middle is stopping this connection. May be a misconfiguration, another firewall, or any other problem.
