### ISSUE TITLE
Trust JKS certificate

### ISSUE THREAD

**Issue by JVT038** [mesacarlos/WebConsole#14]
Hi,
I've an external Synology NAS and that's where I host the website for the console.
My Minecraft Spigot Server is hosted on my own PC. 
When I connect with port 80 / http, the thing works and everything is fine.
But when I connect with port 433 / https / SSL, it won't connect to my Spigot server.
I think it's because or the NAS or the Browser doesn't trust the .JKS certificate I created. 
How do I fix this?

**Comment by mesacarlos** [comment]
Hello,
Are you using a selfsigned certificate? If so, remember to navigate to https://synology_ip:webconsole_port/ before connecting to your server and click on connect anyway. This should make your browser trust your selfsigned cert.

If you already did this, please paste a screenshot of your browser console to check it out (open it pressing F12)

**Comment by JVT038** [comment]
> Hello,
> Are you using a selfsigned certificate? If so, remember to navigate to https://synology_ip:webconsole_port/ before connecting to your server and click on connect anyway. This should make your browser trust your selfsigned cert.
> 
> If you already did this, please paste a screenshot of your browser console to check it out (open it pressing F12)

![image](https://user-images.githubusercontent.com/47184046/75705511-ce6b4e00-5cbb-11ea-9a7b-fb07d6e402e0.png)
This is what I see. 
The 192.168.2.19 is just the internal IP, since the NAS and the PC are on the same LAN.

**Comment by mesacarlos** [comment]
You need to surf to https://192.168.2.19:8080/
Then, try again and problem should be solved.

**Comment by JVT038** [comment]
> You need to surf to https://192.168.2.19:8080/ and click on show advanced settings and then click connect.
> Then, try again and problem should be solved.

Thanks, it worked.

**Comment by mesacarlos** [comment]
Remember that your browser will stop trusting your cert in some hours/days. You will need to repeat this process when it occurs.

**Comment by JVT038** [comment]
> You need to surf to https://192.168.2.19:8080/ and click on show advanced settings and then click connect.
> Then, try again and problem should be solved.

Maybe add these instructions to the SSL page, to prevent further issues with people having the same problem as I had?

**Comment by mesacarlos** [comment]
Please note this is already on the guide.

> Then, to enable connections from your browser remember to first navigate to https://localhost:8080/ (change port if you changed it before at config.yml) and skip the security warning (Click on connect anyway). This is required in order to allow your browser to connect to servers using your own selfsigned certificate. If you don't follow this step, your browser will block connections to your WebSockets Server.
> NOTE: Your browser will stop trusting your certificate in some hours/days, this will cause WebConsole being unable to connect to your server. To solve this, repeat this last step (Just browse to the URL and click on connect anyway)
