### ISSUE TITLE
I try to connect the spigot console to my website

### ISSUE THREAD

**Issue by Warelkill** [mesacarlos/WebConsole#144]
Hello. I see your big code and I love it. I would like to do the same things on my website for personal activity but I tried to see how you connect the spigot server and the website but I can't read your code.  lol.   Can we discuss on discord or something else.

PS: Sorry for my English. I'm a truth french.

Warelkill

**Comment by Warelkill** [comment]
Sorry but i don't how to contact you

**Comment by mesacarlos** [comment]
Hello, here you have videos regarding how to configure and connect the plugin

https://www.youtube.com/watch?v=afzs_HSbrgg
https://www.youtube.com/watch?v=XWCZT4MFYYQ
