### ISSUE TITLE
I'm sorry, I really don't know how to work with clients.

### ISSUE THREAD

**Issue by CyberFIowey** [mesacarlos/WebConsole#148]
I put the plugin on my server, left the port, replaced the current password and user name, and I can't log on to the server on the site without using the clients because there is the wrong connect button, I just don't understand something or it doesn't work for me. I'm sorry again, I just wanted to understand if I'm stupid or if it just doesn't work.

**Comment by CyberFIowey** [comment]
ok maybe my server core not compatible this plugin

**Comment by mesacarlos** [comment]
Hi, what version of Spigot/Paper/Bukkit you are using?
What specific error does it display?
