### ISSUE TITLE
Can not connect to webconsole server

### ISSUE THREAD

**Issue by DenEric** [mesacarlos/WebConsole#149]
I have the webconsole version 2.4.1 running on the spigot minecraft server.
And I have the client configured on a nginx webserver the same machine.
I can communicate with the server:
./websocat.aarch64-unknown-linux-musl ws://localhost:5555
{"status":401,"statusDescription":"Login Required","message":"Verbinding gestart, wachtend op inloggen"}

but if I try to configure a server on the console I get a connection error:

Connection was lost with the server. This can be caused by:
Server was closed intentionally.
Port is not opened on your host. In this case, troubleshoot using a port checker and recheck your firewall or router

![image](https://github.com/mesacarlos/WebConsole/assets/58823646/871d0c5a-af24-469d-9254-686d5f5f0f9f)

Any assistance would be appreciated

**Comment by LOLYAYDEV** [comment]
do you still need assistance? XD

**Comment by DenEric** [comment]
In the meantime everything is fixed.

Thanks
