### ISSUE TITLE
latest.log

### ISSUE THREAD

**Issue by SrYell** [mesacarlos/WebConsole#15]
Hello I have a problem.

When opening the webconsole almost when the server has just been opened, it shows me the log messages (The load and that) but after a certain time if I try to enter again, it appears "Error when trying to read latest.log" And so the rest of the day. Any solution?

(My natural language is Spanish so I'm sorry for bad English)

- This translation was made with Google technology

**Comment by mesacarlos** [comment]
(English translation follows)
Hola,
Antes de sacarte el aviso de que no se puede leer el fichero, debería aparecerte una excepción. Copiala y pegala aquí para ver que puede estar fallando.

------
Hi,
Before that warning, an exception should appear. Copy and paste it here for me to check what may be causing the issue

**Comment by SrYell** [comment]
Hi, sorry for answering late. Here I send the Java exception link:
https://pastebin.com/0K1kAJyT

**Comment by mesacarlos** [comment]
(English translation follows)
Hola de nuevo,
He hecho un pequeño cambio en el plugin que debería solucionar el problema. Puedes descargarte el .jar desde la siguiente dirección:
https://jenkins.mesacarlos.es/job/WebConsole/12/artifact/target/WebConsole-1.5-jar-with-dependencies.jar
El cliente no cambia con respecto a la versión que estas usando ya.
Si puedes, dime si te sigue saliendo o no el error.

---
Hello again,
I have made small changes in the plugin that should fix the problem. You can download the .jar file from:
https://jenkins.mesacarlos.es/job/WebConsole/12/artifact/target/WebConsole-1.5-jar-with-dependencies.jar
The client does not change with respect to the version you are already using.
If you can, please tell me if you still get that exception or not.

**Comment by SrYell** [comment]
Hello!



I'm so sorry I know it's been a long time since this Gmail but believe me
I've been very busy ^^



So far it has worked for me so for the moment I can say that it has been
solved.



Really, thank you for this magnificent plugin and for the attention you
give to this project to have responded very early to my 1 gmail, I hope you
continue like this and good luck with your projects ^^
