### ISSUE TITLE
Unable to connect to server through client interface

### ISSUE THREAD

**Issue by aidenmitchell** [mesacarlos/WebConsole#18]
No errors on the server side, but the interface can't connect for some reason.

**Comment by mesacarlos** [comment]
Hi,
Please send me a copy of your host and port values of your config.yml

**Comment by aidenmitchell** [comment]
Host: 0.0.0.0
Port: 8080

**Comment by mesacarlos** [comment]
Are you using a VPS or dedicated server? Or are you running your server on a home PC

**Comment by aidenmitchell** [comment]
The server is on a home PC.

**Comment by mesacarlos** [comment]
Then try changing 0.0.0.0 to your local IP (probably something like 192.168.1.xxx)
Then try connecting using that IP [on your client](https://i.imgur.com/LLlI722.png).

**Comment by aidenmitchell** [comment]
Oh, the problem was I didn't specify the port in the client, I thought if was 8080 by default. My bad, thanks for your help.
