### ISSUE TITLE
is the connection safe?

### ISSUE THREAD

**Issue by w0lf-dev** [mesacarlos/WebConsole#21]
it is safe to use this
I have not viewed the files, but it seems that it is easy to hack

**Comment by mesacarlos** [comment]
Everything is explained in the README:
For a secure connection between client and server set up SSL following this guide: https://github.com/mesacarlos/WebConsole/wiki/SSL-Configuration
By default connection is not encrypted so it would be possible to read the traffic using Wireshark for example.

Like in all software out there, it may exist some vulnerabilities. As an opensource project, I invite you to install WebConsole and try to find any security flaws, and sending a PR or a issue here.

**Comment by w0lf-dev** [comment]
thanks
