### ISSUE TITLE
better support for people who want to participate in the project

### ISSUE THREAD

**Issue by w0lf-dev** [mesacarlos/WebConsole#22]
i am having trouble navigating the code maybe you can indicate in the readme.md what all the files and code are for.
i would like to fork the project.

(suggestion)
can't add the label lol

**Comment by mesacarlos** [comment]
This review corresponds with v1.5-rev3

```
root directory
│   .gitignore
│   LICENSE
│   phrases.properties
│   phrases_cs.properties
│   phrases_en.properties
│   phrases_es.properties
│   phrases_fr.properties
│   phrases_it.properties
│   phrases_nl.properties
│   phrases_pt.properties
│   phrases_ru.properties
│   phrases_zh.properties
│   plugin.yml
│   pom.xml
│   README.md
│
├───client
│   │   favicon.png
│   │   index.html
│   │   README_AFTER_UPGRADE.txt
│   │
│   ├───scripts
│   │       WebConsole.js
│   │       WebConsoleConnector.js
│   │       WebConsoleJqueryHandler.js
│   │       WebConsoleLanguage.js
│   │       WebConsoleManager.js
│   │       WebConsolePersistenceManager.js
│   │
│   └───styles
│           WebConsole.css
│
└───src
    └───es
        └───mesacarlos
            └───webconsole
                │   WebConsole.java
                │
                ├───minecraft
                │       WebConsoleCommand.java
                │
                ├───util
                │       DateTimeUtils.java
                │       Internationalization.java
                │       LogFilter.java
                │       LoginManager.java
                │
                └───websocket
                    │   WSServer.java
                    │
                    ├───command
                    │       CpuUsageCommand.java
                    │       ExecCommand.java
                    │       LogInCommand.java
                    │       PlayersCommand.java
                    │       RamUsageCommand.java
                    │       ReadLogFileCommand.java
                    │       WSCommand.java
                    │       WSCommandFactory.java
                    │
                    └───response
                            ConsoleOutput.java
                            CpuUsage.java
                            JSONOutput.java
                            LoginRequired.java
                            Players.java
                            Processed.java
                            RamUsage.java
                            UnknownCommand.java
```

## Root directory
Root directory contains server-side translations files (*.properties), Maven pom.xml and plugin.yml

## Client directory

 - **Root**: Favicon and main html file.
 - **Scripts**: Javascript scripts.
	- **WebConsole.js**: Main JS file. It controls the main features of the client.
	- **WebConsoleConnector.js** Basically the WebSocket client. Every object of this class represents a connection to a WS Server. Part of the functions inside are WebSocket event listeners, refer to [https://developer.mozilla.org/es/docs/Web/API/WebSocket](https://developer.mozilla.org/es/docs/Web/API/WebSocket). The rest of the functions are used to send the messages received over WS to all the 'subscribers' (Actually it's just an observer design pattern impl)
	- **WebConsoleJqueryHandler.js** JQuery Event handlers are here. Button click actions, key presses, etc...
	- **WebConsoleLanguage.js** Client translations are stored here. About lang objects: It's key is the HTML id where the phrase should be, and the value, the sentence itself.
	- **WebConsoleManager.js** Basically keeps all WebConsoleConnectors stored inside activeConnections array, and keeps them organized.
	- **WebConsolePersistenceManager.js** Stores settings and servers into your browser localStorage.
 - Styles: WebConsole main css file


## src/es/mesacarlos/webconsole directory

 - **minecraft**: Minecraft commands like /WebConsole  are done here.
 - **util**: General purpose Classes like i18n manager, LoginManager, etc... Read the javadocs for more info.
 - **websocket**: WebSocket files
	 - **command**: WebConsole commands. They all implement WSCommand.java. For a detailed explanation, check out the repo wiki. WSCommandFactory.java creates a HashMap with all the valid WSCommands.
	 - **response**: All clases inside this package implement JSONOutput. Basically they are all the different responses that plugin can send to client.
	 - **WSServer.java**: WebSocketServer implementation.
 -  **WebConsole.java**: Main plugin file. Reads config, creates the WS Server, creates thread....
