### ISSUE TITLE
I can't stop the server properly

### ISSUE THREAD

**Issue by LucidAPs** [mesacarlos/WebConsole#23]
Everything is working great but when i want to stop the server i get this
https://pastebin.com/raw/tzafw1eE
and the server never closes, is there something i can do?

**Comment by mesacarlos** [comment]
Hello,
Thank you for pointing this out. I'm unable to reproduce this issue.
Are you using Spigot or Paper? Can you provide me the version you are using?
What is the Minecraft version you are running?

I just made a small fix, check if this build solves your issue:
https://jenkins.mesacarlos.es/job/WebConsole/22/artifact/target/WebConsole-1.5-jar-with-dependencies.jar

**Comment by LucidAPs** [comment]
I am using paper 313 minecraft 1.15.2, it might be because i am using java 14? The error triggers only when a user has the console open on the websocket and i hit "stop" on my end. It doesn't trigger if there is no one connected. I will test that version you send as soon as i can.

**Comment by LucidAPs** [comment]
The new version you send works with no problems i just did the test :)
