### ISSUE TITLE
No error or console

### ISSUE THREAD

**Issue by TimeSlinky** [mesacarlos/WebConsole#24]
Hello, I just installed the webconsole package and plugin onto my server both running on the same linux machine so localhost port was used. I add the server on the webconsole using 127.0.0.1:port, then nothing happens. It never asked me for the password and then it has not shown anything as the image I added shows. No errors in console, checked and the port I specified is being used listening on 127.0.0.1:port. 

![Screen Shot 2020-05-28 at 6 32 56 PM](https://user-images.githubusercontent.com/10455839/83200745-04309f00-a112-11ea-9e96-8333948518d5.png)

**Comment by mesacarlos** [comment]
Hello,
Are you typing the server address like this? (Typing localhost:port all inside server ip)
![Image](https://i.imgur.com/qDAozgu.png)


You need to type only localhost in server IP, and then the port in "port"

**Comment by TimeSlinky** [comment]
Server Name:
Hub

Server IP:
127.0.0.1:12345

WebConsole Port:
8080

Now that I type that I see why that would be an issue. As I’ve noted two ports for it to look so maybe it’s trying localhost:port:port

I am running a bungee server. So I thought the port would be needed. As when I do this....


Server Name:
Hub

Server IP:
127.0.0.1

WebConsole Port:
8080

It does the same thing, no error and no console. However when I do The same settings as those, but the Server IP as “localhost” it gives me a disconnect error and return to home.

**Comment by mesacarlos** [comment]
Is your WebConsole port 8080?

**Comment by TimeSlinky** [comment]
Okay, I just tried again with these settings

```
Server Name:
Hub

Server IP:
127.0.0.1

WebConsole Port:
8080
```

and got this error on the f12 console (never thought to check that! Thank you for reminding me)
```
WebConsoleConnector.js?v=1.5.2:24 WebSocket connection to 'wss://localhost:8090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED```

**Comment by mesacarlos** [comment]
Apache should not be a problem (unless you run it in same port as WebConsole)

It seems that the server is not alive or something is blocking connection to server.
You said that you are using WebConsole plugin for Bungeecord? If thats the case install it in a Spigot/Paper/Bukkit server and try again.

**Comment by TimeSlinky** [comment]
I do have it in the spigotserver/plugins/ directory. I wanted to run it on a couple of my servers. I have each iteration running on a different port. I checked the ports and they are all active and the console shows they were activated successfully.

**Comment by mesacarlos** [comment]
Thats okay. Lets check config.yml.
What address have you typed as `host`? localhost? If that's the case it should work...

Let's try something else. Are your servers in a VPS/dedicated server? Or are them in your home? (I mean, do you have a public IP for your device?)

**Comment by TimeSlinky** [comment]
I do have "localhost" in the config.yml. I am using a dedicated ubuntu machine. Its not at home, its at a datacenter. I do have a public IP.

**Comment by mesacarlos** [comment]
Perfect. Then change in config.yml from localhost to your dedicated machine public IP. (And type in the client inside Server IP, your dedicated public IP too).

**Comment by TimeSlinky** [comment]
Alright, I tried that. Used my public IP in the config and web client.
```
WebConsoleConnector.js?v=1.5.2:24 WebSocket connection to 'wss://address:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
```

**Comment by mesacarlos** [comment]
SSL is configured in the server?

**Comment by TimeSlinky** [comment]
SSL config is not configured. I thought it was optional os i have not done that. I can try it now with the tutorial in the wiki.

**Comment by mesacarlos** [comment]
Yes thats correct. It's optional. But as i see in the error you sent in the previous message, you are checking that "SSL enabled" checkbox. Uncheck it in your client.

**Comment by TimeSlinky** [comment]
I found the issue. I had SSL off BUT I have web protection enabled by a provider which encrypted my data. I went into its console and allowed those ports past the firewall fixing the issue! This is a temp fix. It seems like allowing the SSL through my provider on those ports will fix my issue and allow the security I want! Thank you for your help in finding that as well as the quick response time.
