### ISSUE TITLE
How can I setup webinterface in Debian 9?

### ISSUE THREAD

**Issue by denzencica** [mesacarlos/WebConsole#3]
Hi,

I tried so many things to setup webinterface to Debian 9 VPS.
Can I get a copy-paste code for download?

**Comment by mesacarlos** [comment]
Hello,
If you are trying to host the web interface in your debian server, you will need to install a http server like apache and then copy WebConsole client files into /var/www/html
You can find help here https://linuxize.com/post/how-to-install-apache-on-debian-9/

**Comment by denzencica** [comment]
Thank you for your answer!
What you suggested worked!
Thank you for your help, have a nice day!
