### ISSUE TITLE
Few questions 

### ISSUE THREAD

**Issue by AzamServer** [mesacarlos/WebConsole#33]
Hi,
I run a private Minecraft server and I am trying to get this plugin installed. I have a few questions about it.

1) Is it still maintained?
2) Can SSL use a Cloudflare Origin Certificate
3) Is there any video to help with the install
4) Does this work with a server on a domain
5) If there is no video, can you please make one

I would really appreciate it if you answered all my questions. Also, please do not reply to this post, and contact me at admin@azamserver.me. Thanks!

**Comment by mesacarlos** [comment]
Hello,
1. Yes. Version 2.0 is coming in the next hours.

2. I'm sorry I think that's not possible. I tried with an user some months ago to make SSL work with cloudflare certs but as far as I know cloudflare does not provide you the private key of your cert.

3. A german youtuber [did a video](https://www.youtube.com/watch?v=XWCZT4MFYYQ) back in September. He used XAMPP to host the client, but that step is not necessary, you can just double-click the index.html file and it will work the same way. Obviously you can also host in a apache2 server or any other. All the processing is done client-side to maximize security so you only need a http server.

4. WebConsole only requires an open port, the same way Minecraft needs port 25565 to work. You can use a domain in top of your IP, of course.

5. See 3.

Hope you get this emailed by GitHub notification system.

**Comment by AzamServer** [comment]
Cloudflare’s Origin Certificate does give a private if you let them generate it for you. Will it work?

**Comment by mesacarlos** [comment]
You will need both the private key an the fullchain.pem. If CloudFlare gives you those files, then you can follow [this guide](https://github.com/mesacarlos/WebConsole/wiki/SSL-Configuration#lets-encrypt-certificate-or-any-pem-certificates) and enable SSL with WebConsole.
