### ISSUE TITLE
Connection was lost with the server you were connected to, probably caused by a server stop.

### ISSUE THREAD

**Issue by Zente1337xyz** [mesacarlos/WebConsole#34]
When i want to connect this show up: 
Connection was lost with the server you were connected to, probably caused by a server stop.

My config: 

https://imgur.com/a/idESjQA

(My server is not stopped)

**Comment by mesacarlos** [comment]
Try with `host` 0.0.0.0

**Comment by Zente1337xyz** [comment]
Now work.Thanks.
