### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AzamServer** [mesacarlos/WebConsole#36]
I keep getting "Connection was lost with the server you were connected to, probably caused by a server stop."

Config.yml:
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: play.azamserver.me
port: 8080
password: *hidden*
language: en

What I put I Webconsole:
Server Name: AzamServer
Server IP: play.azamserver.me
Port: 8080

Port 8080 is forwarded on my router

**Comment by mesacarlos** [comment]
It seems that port is not correctly opened it you check SSL checkbox in the client.
Check if port is opened using [this tool](https://www.yougetsignal.com/tools/open-ports/)

**Comment by mesacarlos** [comment]
Closing this as solved.
This is a recurrent issue when installing WebConsole. If you landed here looking for some help, please check out the discussion at Spigot Forums or some of the closed issues.
As a reference, the most common problems are:

- Port not opened or not reachable from the Internet.
- Incorrect host (I recommend leaving 0.0.0.0)
- Server has SSL enabled and you do not check SSL checkbox in your client or vice-versa.
