### ISSUE TITLE
What kind of mistake is this?

### ISSUE THREAD

**Issue by kirillopnytop** [mesacarlos/WebConsole#37]
![Opera Снимок_2020-06-29_215916_craft-hosting ru](https://user-images.githubusercontent.com/63828171/86022223-41ab8380-ba54-11ea-8d90-c267966439c5.png)

**Comment by mesacarlos** [comment]
Hello, 
Do you have useSSL: true in your config.yml?

**Comment by kirillopnytop** [comment]
Hello,
Yes

**Comment by mesacarlos** [comment]
Then, you need to disable it or follow this guide:
https://github.com/mesacarlos/WebConsole/wiki/SSL-Configuration

**Comment by kirillopnytop** [comment]
I turned it on because
![Opera Снимок_2020-06-29_222054_darkcrafttest 000webhostapp com](https://user-images.githubusercontent.com/63828171/86024153-d3b48b80-ba56-11ea-8c39-b32965dad814.png)

**Comment by mesacarlos** [comment]
If that red warning appears, is because your client is hosted in a https server. You need to follow the SSL configuration guide or use the client in a no-https server (just opening index.html with your browser without hosting the client in a http server will also work)

**Comment by kirillopnytop** [comment]
ok
