### ISSUE TITLE
why are color codes not supported in the console

### ISSUE THREAD

**Issue by kirillopnytop** [mesacarlos/WebConsole#39]
why are color codes not supported in the console
![index html#](https://user-images.githubusercontent.com/63828171/86032577-c3ee7480-ba61-11ea-8d1f-b149ae088f45.png)

**Comment by mesacarlos** [comment]
Colors are supported. If it does not show colors, it may be because it is a log line read from latest.log (the log that you view the first time you connect to the server) or spigot not sending color info to webconsole.

You can check that colors do work typing, for example, /help

**Comment by kirillopnytop** [comment]
No work
![index html#](https://user-images.githubusercontent.com/63828171/86034190-509a3200-ba64-11ea-8383-c37614a524cd.png)

**Comment by mesacarlos** [comment]
It should be something related to your minecraft hosting server provider. Running it on Windows and ubuntu with no issues.

**Comment by kirillopnytop** [comment]
OK
