### ISSUE TITLE
Enable GitHub pages

### ISSUE THREAD

**Issue by MineTheCube** [mesacarlos/WebConsole#41]
Hi!

You should enable GitHub pages on master branch, that way you would provide to anyone a hosted client directly updated from master branch.

If you don't know what I'm talking about, enabling pages from the [settings](https://github.com/mesacarlos/WebConsole/settings) would host the client just like that:
- https://minethecube.github.io/WebConsole/client/

Thanks :)

**Comment by mesacarlos** [comment]
Hi,

Yeah, I tried some months ago enabling it, but GitHub threw me an error (You can see "Page build failed" on commit 9b0e919e02df487e6171cac56d1413e9103ff4e2)
I thought about placing all the versions of the client publicly at my personal webpage, that way i'll not force everyone to update their .jar when pushing a modification to the master branch.

Thank you for this suggestion!

**Comment by mesacarlos** [comment]
Done.
https://mesacarlos.es/webconsole/
