### ISSUE TITLE
I can't connect to my server

### ISSUE THREAD

**Issue by Dr0mus** [mesacarlos/WebConsole#43]
I have done all the steps in github and setup the plugin on my server. The server is online but it still doesn't work. I get this: "**Disconnected** Connection was lost with the server you were connected to, probably caused by a server stop."

**Comment by mesacarlos** [comment]
Hello,
Check using [this tool](https://www.yougetsignal.com/tools/open-ports/) if WebConsole port is opened and reachable. If not, check your firewall (or your router settings if you are hosting from home).

**Comment by Dr0mus** [comment]
checked, the port was not open.
