### ISSUE TITLE
java.io.FileNotFoundException: plugins/WebConsole/keystore.jks (No such file or directory)

### ISSUE THREAD

**Issue by Jvod1324** [mesacarlos/WebConsole#46]
`java.io.FileNotFoundException: plugins/WebConsole/keystore.jks (No such file or directory)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at java.io.FileInputStream.open0(Native Method)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at java.io.FileInputStream.open(FileInputStream.java:195)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at java.io.FileInputStream.<init>(FileInputStream.java:138)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at es.mesacarlos.webconsole.WebConsole.startWS(WebConsole.java:76)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at es.mesacarlos.webconsole.WebConsole.onEnable(WebConsole.java:36)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:124)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:711)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1596)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.util.Util.func_181617_a(SourceFile:46)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:838)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629)
Aug 27 19:12:10 srv1.jvod.online java[11054]: [19:12:10] [Server thread/WARN]:         at java.lang.Thread.run(Thread.java:748)
`

**Comment by mesacarlos** [comment]
Hello,
Recheck that you followed correctly the SSL config guide, or set useSSL to false.
That exception means that the required .jks was not found.
