### ISSUE TITLE
404 WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by ExeRhythm** [mesacarlos/WebConsole#48]
Hello,

I am trying to run a server with this plugin, but when I try to visit localhost:8080 it gives me this error: 404 WebSocket Upgrade Failure. Nothing else. My config.yml is 
`useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 0.0.0.0
port: 8080
language: en
passwords:
  admin:
    user: pass19
  viewer: {}
`

Can anyone help me with this issue? Thanks in advance

**Comment by mesacarlos** [comment]
Hello,
That is the expected response for non-websockets requests to the WebConsole port.
Use the client to connect to your server.
