### ISSUE TITLE
Can't use the client on Android

### ISSUE THREAD

**Issue by Squoshy-Boop** [mesacarlos/WebConsole#54]
Very cool plugin! I used to enter the console via mobile but now with the last version of the plugin it seems that I can't. I'm using Minecraft server version 1.16.2, I could be able to connect to the console on computer but not from my phone, it didn't even show the pop up to enter the password.

**Comment by mesacarlos** [comment]
Hello,
I was able to reproduce this issue. I spent the last hour investigating this issue, being unable to connect from even inside my LAN. Everything was a nonsense

Then I realized that I upgraded to Windows 10 2004 some days ago and that Windows Firewall could be the problem...

Turned off Windows firewall and everything worked. Maybe your problem is similar..

**Comment by Squoshy-Boop** [comment]
> Hello,
> I was able to reproduce this issue. I spent the last hour investigating this issue, being unable to connect from even inside my LAN. Everything was a nonsense
> 
> Then I realized that I upgraded to Windows 10 2004 some days ago and that Windows Firewall could be the problem...
> 
> Turned off Windows firewall and everything worked. Maybe your problem is similar..

Hey, thank you for replying,
I will try, but I guess there should be a better way to solve it, maybe allowing the plugin through the firewall perhaps, but I don't know if that's possible.

**Comment by mesacarlos** [comment]
Yeah, of course, adding a new rule allowing traffic through the WebConsole port will also work (considering that the problem is related to the firewall)

**Comment by Squoshy-Boop** [comment]
I tried both disabling firewall and allowing the port thought the advanced firewall (both UDP and TCP just in case) but the problem persists. I checked the port and it says it's open on the server address.

**Comment by mesacarlos** [comment]
It seems then that the problem is elsewhere.
What browser are you using in your phone?

There was no changes to the WebSocket part in any of the recent updates, so if an older version worked, the new should also work.

What is that value of 'host' in your config.yml?

**Comment by Squoshy-Boop** [comment]
The value set on the Host variable is my computer's ipv4. I tried with both Opera and Chrome.

**Comment by mesacarlos** [comment]
Try changing that to 0.0.0.0

**Comment by Squoshy-Boop** [comment]
Putting 0.0.0.0 lead to the same results as putting my ipv4. Just to be clear, I CAN connect from other wifis (even through mobile data), but ONLY on PC, I CAN NOT connect from any mobile device (it didn't even show to write the password, that's why I think something changed in this client version)

**Comment by Squoshy-Boop** [comment]
I'll try with version 1.5 to see if it's still working

**Comment by Squoshy-Boop** [comment]
I tried with V1.5 but I can't even connect with it now D:

**Comment by Squoshy-Boop** [comment]
Bastante comico que estemos hablando en ingles y recien ahora me doy cuenta que hablas español xD

**Comment by mesacarlos** [comment]
> Bastante comico que estemos hablando en ingles y recien ahora me doy cuenta que hablas español xD

Pues si, :joy:

Parece que el problema está en alguna otra parte, si no fuese así debería de funcionar todo de nuevo con la versión 1.5...
Quizá te ayude saber que puedes probar si puedes acceder al servidor desde un dispositivo entrando en la dirección http://ip_de_tu_server:puerto, debería aparecer algo como esto:

![img](https://i.imgur.com/DuOpOpi.png)

Si te aparece ese mensaje, es que tu navegador conecta correctamente con el servidor de WebConsole. Si no conecta, probablemente tu navegador acabe mostrando un error de timeout.

**Comment by Squoshy-Boop** [comment]
![image](https://user-images.githubusercontent.com/32151264/96540126-37b3c780-1273-11eb-99f9-594282282159.png)
Me sale lo mismo que a vos

**Comment by Squoshy-Boop** [comment]
Tanto en la computadora como en el celular usando la ip publica me sale lo mismo

**Comment by mesacarlos** [comment]
Qué extraño, eso significa que sí se conecta al servidor correctamente...
Has probado usar el modo incógnito en el móvil? Quixas sea algún problema de caché.

O quizás sea por haber marcado la casilla de "SSL activado" o alguna otra configuración incorrecta en el cliente..

**Comment by Squoshy-Boop** [comment]
Creo que sé dónde está el problema, y es que el archivo de configuración está semi actualizado, puesto que tiene parte de cuando sólo había una única contraseña. Ahora mismo no estoy en la computadora, pero es algo como esto:

useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 0.0.0.0
port: 3074
language: es
passwords: contraseñavieja
   admin:
      user1: 5179.0
   viewer: {}

**Comment by Squoshy-Boop** [comment]
Eliminé la configuración para que se genere un nuevo archivo pero tampoco, sigue sin conectar desde el teléfono, ni siquiera sale para poner la contraseña

**Comment by mesacarlos** [comment]
Al final lograste conectarte desde Android?

Cierro la issue ya que en mi caso es irreproducible
