### ISSUE TITLE
WebConsole over Node.js application

### ISSUE THREAD

**Issue by karelkryda** [mesacarlos/WebConsole#56]
I'm trying to connect to the console via the Node.js application. How can I bypass adding the server and entering the password so that I can enter the commands directly?

**I'm sorry to use the issue**

**Comment by mesacarlos** [comment]
Hello,

I don't understand your question. ¿Are you developing a NodeJS app and you want to use this plugin to connect to a server?
Don't be sorry! Issues are for this purpose here :)

**Comment by karelkryda** [comment]
I'm trying to create a Discord bot that will be able to control the server using the console

**Comment by karelkryda** [comment]
For example, is it possible to send a request from Node.js using, for example, POST without having to remake the WebConsole client?

**Comment by mesacarlos** [comment]
Yeah, it is possible. Check out #55.
I posted there the minimum Javascript code needed to connect to a server.

**Comment by karelkryda** [comment]
@mesacarlos Can I use this in Node.js?

https://www.npmjs.com/package/websocket

**Comment by mesacarlos** [comment]
Probably yes, you need a websocket **client**, and that package implements it.

**Comment by karelkryda** [comment]
Works, thanks

![image](https://user-images.githubusercontent.com/59953812/99074551-3d71a400-25b8-11eb-8dc7-fe25fd5b6f17.png)

**Comment by mesacarlos** [comment]
Cool!
