### ISSUE TITLE
RAM usage is incorrect

### ISSUE THREAD

**Issue by olidem00** [mesacarlos/WebConsole#58]
I have been experimenting with your API to include my server stats on a web app. I did notice that the memory reading was incorrect:
Actual value:
![image](https://user-images.githubusercontent.com/51768714/100521646-f0263280-3172-11eb-82a7-e8afd8874caf.png)
Value displayed:
![displayed](https://user-images.githubusercontent.com/51768714/100521716-3da29f80-3173-11eb-836c-4be03fa222ec.png)

I know someone already pointed this out in issue #19, and you explained that it was caused by the heap size being different than the actual memory size.

I have reviewed your source code, and it appears the issue comes from lines 15 to 17 in WebConsole-2.0-rev2\src\es\mesacarlos\webconsole\websocket\command\RamUsageCommand.java:

![image](https://user-images.githubusercontent.com/51768714/100521768-a853db00-3173-11eb-83c8-270bbf5a25b1.png)

You see, maxMemory() is the maximum heap size, whereas freeMemory() is the free heap size memory. Therefore, in order to get usage, you need to modify the code to this:
![image](https://user-images.githubusercontent.com/51768714/100521788-cae5f400-3173-11eb-9d07-70e9ec1e8919.png)

This resolved my issue, as totalMemory() is the current heapsize, which is more often than not way lower than the actual heap limit:
![image](https://user-images.githubusercontent.com/51768714/100522606-5e212880-3178-11eb-880a-ec6466e94487.png)

Other than that, I love your plugin, and it has been exactly what I was looking for, so many thanks for making it 👍 

Hope this could help !

**Comment by mesacarlos** [comment]
Hello,

Thank you for your research and posting this issue!
I didn't noticed the problem because I was running my server with -Xmx1G -Xms1G params, so every time I tested it it was OK because maxMemory() and totalMemory() were basically the same...

I'm releasing a new version now with this issue solved.
Thank you again!
