### ISSUE TITLE
Support for Dynmap 

### ISSUE THREAD

**Issue by JVT038** [mesacarlos/WebConsole#6]
Hi,
I've an idea for this plugin with support for dynmap.
If the plugin checks the existence of dynmap, then if true it will be showing an iframe with the minecraft world.

**Comment by w0lf-dev** [comment]
you can just do it with an i-frame and connect it to the port of dynmap (ask the port numbers in the configuration)

**Comment by w0lf-dev** [comment]
i am working on it
