### ISSUE TITLE
Need a precision (bukkit or not bukkit ?)

### ISSUE THREAD

**Issue by MaelREBOUX** [mesacarlos/WebConsole#60]
Hello,

I'm a newbye in the minecraft world and a I want to install you webconsole.

By following your documentation I'm blocked at step 2 : "Open and close your server to generate the config.yml file and open it."

**What does it means "Open and close your server" ?**

The doc does not tell what to do with the jar once downloaded. 
By searching on the web I guess that you plugin is dependant to the bukkit version of minecraft not the original minecraft jar server ?

Because I have any "Plugin" folder on my server actually.

Thank you to bring precision for any dependances because it is not clear for me actually.

**Comment by mesacarlos** [comment]
Hello,
Bukkit/Spigot/PaperMC server plugins are all the same: A .jar file. The folder structure of a bukkit/spigot server is something like the following:

![structure](https://i.imgur.com/bkrsoX7.png)

To install any plugin, you need to download the .jar file of the plugin (WebConsole.jar in this case) to the "plugins" folder of your bukkit or spigot server:

Screenshot of my plugins folder
![plugins folder](https://i.imgur.com/e9nc37W.png)

The folders you see there ill automatically generate when you run your server, and they contain the configuration files for your installed plugins. For example, for WebConsole, it is generated the WebConsole folder, and inside of it is generated a config.yml file (the one refferred by the docs).

Answering to your question: Yu do not run the .jar files of your plugins. You run the jar file of your server (bukkir.jar or spigot.jar or if a .bat file if you made it). Bukkit will be the one that opens and executes the plugins stored inside the plugins folder.

**Comment by MaelREBOUX** [comment]
Hello ! You are quick !

In the meantime I just set up a Bukkit version Minecraft server. And now I see all the structure and the plugin folder.

So I recommend you just to add a little sentence to precise the dependency to the bukkit version.

Now : testing you webconsole !

have a good day.

**Comment by MaelREBOUX** [comment]
Up and running : great job.

```bash
cd /data/craftbukkit/plugins/
wget https://github.com/mesacarlos/WebConsole/releases/download/v2.1/WebConsole-2.1.jar
mv WebConsole-2.1.jar WebConsole.jar
```

edit config.yml file, restart the minecarft server

```bash
apt install nginx
 
cd /var/www/html/
wget https://github.com/mesacarlos/WebConsole/releases/download/v2.1/client-v2.1.zip
unzip client-v2.1.zip
mv client console
```

http://{my-server}/console/
