### ISSUE TITLE
Is it Possible to Make a Discord bot link?

### ISSUE THREAD

**Issue by Rithul-Kamesh** [mesacarlos/WebConsole#61]
Hi, I Had a command in my bot which allowed me to whitelist members through a discord console, But Due to Sudden Conflicts, How do I link it to this console so that I can Make my admins' Lives easier?

p.s: Please Hook me Up on discord So Its Easier

**Comment by mesacarlos** [comment]
Hello,
You can check [here](https://github.com/mesacarlos/WebConsole/wiki/WebSocket-commands-and-responses) how to communicate with the server.
Also, a demo written in JS is available [here](https://jenkins.mesacarlos.es/job/WebConsole/lastSuccessfulBuild/artifact/API_js.zip).
