### ISSUE TITLE
is it possible to save servers to the panel?

### ISSUE THREAD

**Issue by TamaKaiNya** [mesacarlos/WebConsole#63]
I'm hosting my panel on my website and would like my staff not to have the add a server profile every time they login from a new device

**Comment by mesacarlos** [comment]
Hi,
Currently that feature is not available as the client is pure client-side. You could add a piece of code to, for example, WebConsoleJqueryHandler.js, to automatically add your servers:

```
	persistenceManager.replaceAllServers([
	{
		serverName: "My first server",
		serverURI: "ws://localhost:8080",
		serverPassword: "pass1234",
	},
	{
		serverName: "My second server",
		serverURI: "wss://example.com:8080" },
		//serverPassword is optional.
	]);
```
So the final file looks like: https://gist.github.com/mesacarlos/959c1b6d909326379e00692cca5cceba

**Comment by TamaKaiNya** [comment]
so like https://gist.github.com/TamaKaiNya/b70b7d320a43e716a2b329c703e7fce5

**Comment by mesacarlos** [comment]
Correct!
Just add again /** at the very first of the file or remove that comment completely.

Note that if you enabled SSL in the WebConsole Server you need to change from ws to wss in the `serverURI: "ws://mc.mazemoi.com:6486",` line (so it looks like `serverURI: "wss://mc.mazemoi.com:6486",`)
Again, this only applies if you enabled SSL.

**Comment by TamaKaiNya** [comment]
the server does not show up on the list

**Comment by mesacarlos** [comment]
Recheck that you did everything correct, and the file was correctly updated.
