### ISSUE TITLE
No data for CPU usage

### ISSUE THREAD

**Issue by ohabu** [mesacarlos/WebConsole#64]
It was working just before upgrading Java 8 32bit to 64bit version.
![image](https://user-images.githubusercontent.com/63399858/109330155-6e769b80-786c-11eb-97d2-aad2469aab81.png)

{"status":1001,"statusDescription":"CPU Usage","usage":NaN,"message":"Usage is ?%"}

Edit: I am not able to reproduce the bug on another system.

**Comment by mesacarlos** [comment]
Hi,

Are you running Windows 10? I'm also not able to reproduce the issue installing Java x86 and then upgrading to x64.

**Comment by ohabu** [comment]
It's related to 64bit version. 32bit version works fine.  
Tried 64bit java  version 1.8 and version 15.
Java 1.8 (Java HotSpot(TM) Client VM 25.281-b09) (1.8.0_281)
Java 15 (Java HotSpot(TM) 64-Bit Server VM 15.0.2+7-27)
Specs:
Java 1.8 (Java HotSpot(TM) Client VM 25.281-b09) (1.8.0_281)
Host: Windows 10 20H2 64Bit
minecraft server version 1.16.5
Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by ohabu** [comment]
Hi,

I dug it down as much as i can.
This issue is related to either Java or Windows 10.

**Comment by mesacarlos** [comment]
Hi,
Just tested again with Java 1.8.0_281 x64 and, sadly, still unable to reproduce the issue :(

**Comment by mesacarlos** [comment]
Also tested with Windows 10 20H2, not able to reproduce the issue

**Comment by ohabu** [comment]
I think it's a localization issue on Java/Windows side. Changing system language to English did the trick. 

English installation of Windows 10 which is translated to Turkish has no issues.
Turkish installation of Windows 10 which is translated to English has no issues.
English installation of Windows 10 has no issues.
Turkish installation of Windows 10 **has issues**.

Sadly, I'm too lazy to open an issue for this. 

Thanks for your help.
