### ISSUE TITLE
Config file reset when add viewer

### ISSUE THREAD

**Issue by jobbedf** [mesacarlos/WebConsole#68]
Hello, I cannot connect to the web console client. I have entered the correct port, tested with 0.0.0.0 in the config, entered the correct ip there too but nothing worked. When I test the port in a port tester it says the port is closed but the hosting says it is not. The hosting also says that it is because I have to create a database for the passwords.

**Comment by jobbedf** [comment]
Yes, It works. But I changed ad added users in the config file but when I restart the server, the users will be removed.

**Comment by jobbedf** [comment]
When I enter a login for viewer and I restaert the server, the config file is reseted.

**Comment by mesacarlos** [comment]
Hi,
That problem may be related to some other plugin installed on your server. Someone already had a similar problem and asked here in Github or Spigot forums, but I think he/she never found why that happened.

**Comment by jobbedf** [comment]
I haver this plugins: 
![image](https://user-images.githubusercontent.com/66115112/111684256-c2025680-8826-11eb-942a-957d5763145c.png)

**Comment by mesacarlos** [comment]
Sorry, I am not able to reproduce the issue.
Maybe it is related to system permissions, or maybe it is a Bukkit/Spigot/PaperMC issue.
