### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Gadiel-Scharf** [mesacarlos/WebConsole#71]
Hello, good morning, I was able to publish the page but when I add the server it gives me a ports error, is there any means of communication where we can talk better?

**Comment by mesacarlos** [comment]
Hello,
Can you please post a screenshot of the values you enter in the "add server" form?

Like this:
![image](https://i.imgur.com/fWUbRG2.png)

**Comment by Gadiel-Scharf** [comment]
Yeah bro

![image](https://user-images.githubusercontent.com/68600690/113486881-47267600-948b-11eb-8a40-50254f618248.png)

**Comment by Gadiel-Scharf** [comment]
At the config 

![image](https://user-images.githubusercontent.com/68600690/113486894-5c030980-948b-11eb-85ee-23d626794557.png)

**Comment by mesacarlos** [comment]
As I can see, you installed the webserver (Apache/NGINX) on the server on the port 80. Then, you need to use a different port in the config.yml for the plugin. And then type that port in the "Add server" form

**Comment by Gadiel-Scharf** [comment]
Great, it works, thank you very much

**Comment by mesacarlos** [comment]
Cool! :)
