### ISSUE TITLE
Does not work. Idk how to fix it

### ISSUE THREAD

**Issue by FreshImmuc** [mesacarlos/WebConsole#72]
I put the ZIP into my html apache folder. Installed the plugin but If I try to add a Server it says that it got disconnected

**Comment by mesacarlos** [comment]
Hello,
Recheck that the port you typed inside config.yml is open to the internet using a toll like https://www.yougetsignal.com/tools/open-ports/
Also check that the ip and port you type inside the client are your server IP, and the port the one specified in config.yml

**Comment by FreshImmuc** [comment]
it says that the port is closed
how can I open it?

**Comment by mesacarlos** [comment]
Check your firewall rules or your router in your server to open the port.

**Comment by FreshImmuc** [comment]
how

**Comment by FreshImmuc** [comment]
is there a file?

**Comment by mesacarlos** [comment]
It depends on the OS your server is running.
You can find detailed tutorials on the web for your
