### ISSUE TITLE
[Feature] Whitelist and Blacklist support

### ISSUE THREAD

**Issue by awesomemoder316** [mesacarlos/WebConsole#79]
Instead of just black and white write access for the Webconsole, how about a whitelist/blacklist for each admin profile?

**Comment by mesacarlos** [comment]
Hi,
Do you mean a permissions system, like a list for each user containing each action (view console, allow to execute a list of commands, deny to execute another list of commands, etc.)

**Comment by awesomemoder316** [comment]
Yeah, that's what I meant. Sorry about the lack of clarity.

I intially hoped that intigration with LP or Pex would be possible, but seeing as consoles have all permissions and is non revokeable, the next best thing is a whitelist and blacklist of commands for each admin user.
