### ISSUE TITLE
Add a server management in the client.

### ISSUE THREAD

**Issue by ConaII** [mesacarlos/WebConsole#88]
IT sucks currently having to use the server list and we can't even delete servers without connecting.
It could be something like this.
A list of servers and you can change the password details, the port, ip, name, delete and clone.
![image](https://user-images.githubusercontent.com/72966048/144691357-2f21fc6d-3e19-4eaf-9acc-3638f4f99053.png)

**Comment by mesacarlos** [comment]
Hello,
It is true that the system to manage server today sucks. I'm aware that the project has a lot of new features pending to be implemented and already implemented ones like the client need a retouch (I thought rewriting the client using Angular with new cool features like this one, better design, etc..) but unfortunately, at this moment I do not have the time needed to do so.

**Comment by mesacarlos** [comment]
Hi!
Just wanted to say that this is something i'm currently working on! I'm hoping to have news about this in the following weeks.
I have also plans to improve the server (as currently some features like TPS do not work properly..)

**Comment by mesacarlos** [comment]
Done! https://github.com/mesacarlos/WebConsole/commit/7d13d219d18cd535e6447cd6309712b65016c5ac

You can start trying it out. Version v2.4 of the plugin is fully compatible with this v2.5 beta version:
https://mesacarlos.es/webconsole/client-v2.5-beta/
You can also download this brand new client from https://jenkins.mesacarlos.es/job/WebConsole/85/artifact/client.zip

Note that, for now, it is required to run it in a web server (Apache, NGINX, ...), plus it needs to be in the root directory of the domain or subdomain. I'll be fixing this issues in the following days.
Also, only English and Spanish are available.

Hope you guys like it!
![index](https://i.imgur.com/5MHjLUI.png)
![add](https://i.imgur.com/JaKkvF6.png)
![edit](https://i.imgur.com/fg0xBGC.png)
![console](https://i.imgur.com/YleTk9B.png)
![settings](https://i.imgur.com/WehZjOs.png)
